services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi-app
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://user:password@db:5432/huriganadb
            GEMINI_API_KEY: ${GEMINI_API_KEY}
            SECRET_KEY: ${SECRET_KEY}

    db:
        image: postgres:13-alpine
        container_name: hurigana-db
        environment:
            POSTGRES_DB: huriganadb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data: